import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import products from '../products.json';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header>
          <a href="#">
            <img src="images/logo.png" alt="Nike"></img>
          </a>
          <nav>
            <a href="">Celulares Novos</a>
            <a href="">Celulares Usados</a>
            <a href="">Suporte</a>
            <a href="">Contato</a>
          </nav>
        </header>

        <div className={styles.center} id="produto" >
          {products.map(product => {
            return (
              <div key={product.id} className={styles.card}>
                <img src={product.image} alt={`Preview of ${product.titulo}`} />
                <h3>{product.titulo}</h3>
                <p>{product.descricao}</p>
                <p>${product.preco}</p>
                <p>
                  <button>Adicionar ao Carrinho</button>
                </p>
              </div>
            );
          })}
        </div>
        <footer>
          <p>Todos os direitos reservados - Cellular Store</p>
        </footer>


      </main >
    </>
  )
}
